# Generated by Django 3.2.4 on 2023-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=50)),
                ('Baner_Display', models.BooleanField(default=False)),
            ],
        ),
    ]
