# Generated by Django 3.2.4 on 2023-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_baner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='service_profile/'),
        ),
    ]
