# Generated by Django 3.2.4 on 2023-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='instagram',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
