# Generated by Django 3.2.4 on 2023-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20230429_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
