# Generated by Django 3.2.4 on 2023-05-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='service_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='service_profile/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
