# Generated by Django 3.2.4 on 2023-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_picture/p1.png', null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='profile_pic',
            field=models.ImageField(default='service_profile/download.png', null=True, upload_to='service_profile/'),
        ),
    ]
