# Generated by Django 4.1.3 on 2023-05-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20230509_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_picture',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
    ]
